services:
  # Posgres DB and Admin
  pgdatabase:
    container_name: pgdatabase
    image: postgres:16
    environment:
      POSTGRES_USER: ${PGUSER:-root}
      POSTGRES_PASSWORD: ${PGPASSWORD:-root}
      POSTGRES_DB: ${PGDATABASE:-postgres}
    volumes: 
      - pg_data:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
    restart: always
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes: 
      - pgadmin_data:/var/lib/pgadmin
    ports: 
      - 8080:80

volumes:
  pg_data:
  pgadmin_data:
